name: Fetch CloudFlare IPv6 (Python-Playwright)

on:
  schedule:
    - cron: "0 8 * * *"   # UTC 08:00
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # 必须给写权限才能 push

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 用默认 token 即可

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps & browser
        run: |
          pip install --upgrade pip
          pip install playwright
          playwright install chromium --with-deps

      - name: Run crawler & write ipv6.txt
        run: python get_cf_ipv6.py > ipv6.txt

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ipv6.txt
          # 有变化再 commit，避免空 commit
          git diff --cached --quiet || (git commit -m "Update ipv6.txt $(date -u +%F_%H:%M)" && git push)
