name: Update IP List

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch: # Allow manual trigger
  push: # Trigger on push

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Updated to latest version for reliability

    - name: Set up Python
      uses: actions/setup-python@v5 # Updated to latest version
      with:
        python-version: '3.9' # Keep Python 3.9 as specified

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp requests beautifulsoup4 selenium webdriver_manager

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Run script
      run: python ${{ github.workspace }}/collect_ips.py

    - name: Commit and push changes
      run: |
        git config --global user.email "tianshideyou@proton.me"
        git config --global user.name "tianshipapa"
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt
          git commit -m "Automatic update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
